version: '3.8'

networks:
  quiz:
    external: true

services:
  account_service:
    image: account_service:0.0.1
    container_name: account_service
    environment:
      MYSQL_URL: ${MYSQL_URL}
      REDIS_URL: ${REDIS_URL}
      NOTIFICATION_URL: ${NOTIFICATION_URL}
      KEY_JWT: ${KEY_JWT}
    ports:
      - "8080:8080"
    networks:
      - quiz

  chat_service:
    image: chat_service:0.0.1
    container_name: chat_service
    environment:
      MONGODB_URL: ${MONGODB_URL}
      ACCOUNT_URL: ${ACCOUNT_URL}
      KEY_OPENROUTER: ${KEY_OPENROUTER}
    ports:
      - "8081:8081"
    networks:
      - quiz
    depends_on:
      - account_service

  quiz_service:
    image: quiz_service:0.0.1
    container_name: quiz_service
    environment:
      MONGODB_URL: ${MONGODB_URL}
      ELASTIC_URL: ${ELASTIC_URL}
      ACCOUNT_URL: ${ACCOUNT_URL}
      NOTIFICATION_URL: ${NOTIFICATION_URL}
      KEY_JWT: ${KEY_JWT}
    ports:
      - "8082:8082"
    networks:
      - quiz
    depends_on:
      - account_service

  notification_service:
    image: notification_service:0.0.1
    container_name: notification_service
    environment:
      MONGODB_URL: ${MONGODB_URL}
      ACCOUNT_URL: ${ACCOUNT_URL}
      KEY_JWT: ${KEY_JWT}
      KEY_BREVO: ${KEY_BREVO}
    ports:
      - "8083:8083"
    networks:
      - quiz
    depends_on:
      - account_service


  api_gateway:
    image: api_gateway:0.0.1
    container_name: api_gateway
    environment:
      ACCOUNT_URL: ${ACCOUNT_URL}
      CHAT_URL: ${CHAT_URL}
      QUIZ_URL: ${QUIZ_URL}
      NOTIFICATION_URL: ${NOTIFICATION_URL}
    ports:
      - "8888:8888"
    networks:
      - quiz
    depends_on:
      - account_service
      - chat_service
      - quiz_service
      - notification_service