server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account_service
          uri: ${ACCOUNT_URL:http://localhost:8080}
          predicates:
            - Path=/account_service/**


        - id: chat_service
          uri: ${CHAT_URL:http://localhost:8081}
          predicates:
            - Path=/chat_service/**


        - id: quiz_service
          uri: ${QUIZ_URL:http://localhost:8082}
          predicates:
            - Path=/quiz_service/**


        - id: notification_service
          uri: ${NOTIFICATION_URL:http://localhost:8083}
          predicates:
            - Path=/notification_service/**

