server:
  port: 8082
  servlet:
    context-path: /quiz_service


spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://root:root@localhost:27017/QUIZZ?authSource=admin}

    elasticsearch:
      uris: ${ELASTIC_URL:http://localhost:9200}


app:
  service:
    account: ${ACCOUNT_URL:http://localhost:8080}/account_service
    notification: ${NOTIFICATION_URL:http://localhost:8083}/notification_service

key:
  jwt:
    value: ${KEY_JWT:12345678901234567890123456789012}