server:
  port: 8080
  servlet:
    context-path: /account_service


spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://root:root@localhost:27017/QUIZZ?authSource=admin}


key:
  jwt:
    value: ${KEY_JWT:12345678901234567890123456789012}